version: '3'
services:
  api:
    restart: on-failure
    build: 
      context: .
      dockerfile: 'PaymentGateway/Dockerfile'
    depends_on: 
      - rabbitmq
      - fakebank
    ports:
      - "8085:80"
      - "4431:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Certificates__Default__Path=/app/Infrastructure/Certificate/certificate.pfx 
      - Kestrel__Certificates__Default__Password=password 
      - ASPNETCORE_URLS=https://+:443;http://+:80 
    volumes:
      - C:\temp\:/app/Infrastructure/Certificate
  fakebank:
    image: rodolpheche/wiremock
    container_name: wiremock-standalone
    expose: 
      - 8080
    volumes:
    - "./deploy/wiremock:/home/wiremock"
    command:
    - -verbose
    - -global-response-templating
  rabbitmq:
    hostname: rabbitmq
    image: 'bitnami/rabbitmq:latest'
    ports:
      # HTTP management UI
      - '15672:15672'
    expose:
      - 5672
 