version: '3'
services:
  # api:
  #   build: "PaymentGateway/."
  #   ports:
  #     - "3000:80"
  wiremock:
    image: rodolpheche/wiremock
    container_name: wiremock-standalone
    ports: 
      - "8080:8080"
    volumes:
    - "./deploy/wiremock:/home/wiremock"
    command:
    - -verbose
    - -global-response-templating

 