version: '3'
services:
  api:
    build: "PaymentGateway/."
    ports:
      - "44375:80"
  wiremock:
    image: rodolpheche/wiremock
    container_name: wiremock-standalone
    ports: 
      - "8080:8080"
    volumes:
    - "./deploy/wiremock:/home/wiremock"
    command:
    - -verbose
    - -global-response-templating
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '8081:15672'
 