version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01 
    working_directory: ~/payment-gateway  
    steps:
      - checkout
      - run: 
          name: Building Docker Image
          command: docker build -f './PaymentGateway/Dockerfile' .
  test:
      machine:
          image: ubuntu-1604:202004-01 
      working_directory: ~/payment-gateway  
      steps:
        - checkout
        - run: 
            name: Install Dotnet
            command: | 
              wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
              sudo dpkg -i packages-microsoft-prod.deb
              sudo apt-get update
              sudo apt-get install -y dotnet-sdk-3.1 
        - run:
            name: Running Unit Tests
            command: dotnet test './PaymetGateway.UnitTests/'

workflows:
  version: 2
  Workflow:
    jobs:
      - test
      - build:
          requires:
            - test

