 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     machine:
        image: ubuntu-1604:202004-01
     working_directory: ~/payment-gateway  
     steps:
       - checkout
       - run:
          name: Running Unit Tests
          command: dotnet test
          working_directory: dotnet test .\PaymetGateway.UnitTests\
       - run: 
          name: Building Docker Image
          command: docker build -f './PaymentGateway/Dockerfile' .
       
